name: "\U0001F41E Bug Report"
description: Report an issue with electron-vite
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: electron-vite-version
    attributes:
      label: Electron-Vite Version
      description: What version of Electron-Vite are you using?
    validations:
      required: true
  - type: input
    id: electron-version
    attributes:
      label: Electron Version
      description: What version of Electron are you using?
    validations:
      required: true
  - type: input
    id: vite-version
    attributes:
      label: Vite Version
      description: What version of Vite are you using?
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://github.com/alex8088/electron-vite#readme).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.
          required: true
